{
    "openapi": "3.0.3",
    "info": {
        "title": "ATM Sehat RESTful API",
        "version": "1",
        "description": "OpenAPI for ATM Sehat",
        "termsOfService": "https://tsi.co.id",
        "contact": {
            "name": "Khairon, S.Kep., Ners, S.Kom",
            "email": "khaironbiz@gmail.com",
            "url": "https://www.khairon.my.id"
        },
        "license": {
            "name": "APACHE 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "servers": [
        {
            "description": "ATM Sehat RESTful API Server",
            "url": "https://{environment}.tsi.co.id/api/v1",
            "variables": {
                "environment": {
                    "description": "Server Environment",
                    "default": "dev",
                    "enum": [
                        "dev",
                        "qa",
                        "prod"
                    ]
                }
            }
        }
    ],
    "externalDocs": {
        "description": "Youtube Tele Sehat Indonesia",
        "url": "https://www.youtube.com/@telehealthindonesia8220"
    },
    "paths": {
        "/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Login account",
                "description": "Login user with email and password",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/login"
                            },
                            "examples": {
                                "Khairon": {
                                    "description": "Example login for Khairon",
                                    "value": {
                                        "email": "khaironbiz@gmail.com",
                                        "password": "Rahasia"
                                    }
                                },
                                "Anisa Fitri Laila": {
                                    "description": "Example login for Anisa Fitri Laila",
                                    "value": {
                                        "email": "anisa.fitri@gmail.com",
                                        "password": "RahasiaBanget"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Succes Login User",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Users"
                                },
                                "examples": {
                                    "khairon": {
                                        "description": "Example login users Khairon",
                                        "value": {
                                            "status": "Success",
                                            "status code": 200,
                                            "content": {
                                                "id": 1,
                                                "name": "khairon",
                                                "nik": 1234567891123123,
                                                "email": "khaironbiz@gmail.com"
                                            }

                                        }
                                    },
                                    "anisa": {
                                        "description": "Example login users Anisa Fitri Laila",
                                        "value": {
                                            "status": "Success",
                                            "status code": 200,
                                            "content":{
                                                "id": 2,
                                                "name": "Anisa Fitri Laila",
                                                "nik": 1234567891123456,
                                                "email": "anisa.fitri@gmail.com"
                                            }

                                        }
                                    }
                                }
                            }
                        }

                    },
                    "401": {
                        "description": "User Not Authorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "failed": {
                                        "description": "Not Authorized",
                                        "value": {
                                            "success": false,
                                            "message": "Not Authorized"
                                        }
                                    }
                                }
                            }
                        }
                    },

                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "TsiAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get all users",
                "description": "Get all active users",
                "parameters": [
                    {
                        "name": "Is_active",
                        "in": "query",
                        "required": true,
                        "description": "Is include active",
                        "schema": {
                            "type": "boolean",
                            "nullable": false,
                            "default": true
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": false,
                        "description": "Filter users by name",
                        "schema": {
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "examples": {
                            "Khairon": {
                                "description": "Example name Khairon",
                                "value": "Khairon"
                            },
                            "Anisa Fitri": {
                                "description": "Example name Anisa Fitri",
                                "value": "Anisa Fitri"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success get all users",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ArrayUsers"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success get all users",
                                        "value": [
                                            {
                                                "id": "1",
                                                "name": "Khairon Anas",
                                                "email": "khaironbiz@gmail.com",
                                                "phone": "081213798746",
                                                "nik": "1234567891123456"
                                            },
                                            {
                                                "id": "2",
                                                "name": "Anisa Fitri Laila",
                                                "email": "anisa.fitri@gmail.com",
                                                "phone": "0817250909",
                                                "nik": "1234567891123456"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TsiAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create new todolist",
                "description": "Create new todolist to database",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateUsers"
                            },
                            "examples": {
                                "khairon": {
                                    "description": "Example create users Khairon",
                                    "value": {
                                        "name": "khairon",
                                        "nik": 1234567891123456,
                                        "email": "khaironbiz@gmail.com"
                                    }
                                },
                                "anisa": {
                                    "description": "Example create users Anisa Fitri Laila",
                                    "value": {
                                        "name": "Anisa Fitri Laila",
                                        "nik": 1234567891123456,
                                        "email": "anisa.fitri@gmail.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success create users",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Users"
                                },
                                "examples": {
                                    "khairon": {
                                        "description": "Example create users Khairon",
                                        "value": {
                                            "id": 1,
                                            "name": "khairon",
                                            "nik": 1234567891123456,
                                            "email": "khaironbiz@gmail.com"
                                        }
                                    },
                                    "anisa": {
                                        "description": "Example create users Anisa Fitri Laila",
                                        "value": {
                                            "id": 2,
                                            "name": "Anisa Fitri Laila",
                                            "nik": 1234567891123456,
                                            "email": "anisa.fitri@gmail.com"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}": {
            "put": {
                "security": [
                    {
                        "TsiAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update existing users",
                "description": "Update existing users in database",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/UserId"
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateUsers"
                            },
                            "examples": {
                                "Khairon": {
                                    "description": "Example update user Khairon",
                                    "value": {
                                        "id": 1,
                                        "name": "Khairon",
                                        "nik": 1234567891123456,
                                        "email": "khaironbiz@gmail.com"
                                    }
                                },
                                "Anisa Fitri": {
                                    "description": "Example update User Anisa Fitri Laila",
                                    "value": {
                                        "id": 2,
                                        "name": "Anisa Fitri Laila",
                                        "nik": 1234567891123456,
                                        "email": "anisa.fitri@gmail.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success update users",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Users"
                                },
                                "examples": {
                                    "Khairon": {
                                        "description": "Success create khairon users",
                                        "value": {
                                            "id": "1",
                                            "name": "Khairon",
                                            "nik": "1234567891123456",
                                            "email": "khaironbiz@gmail.com"
                                        }
                                    },
                                    "Anisa Fitri": {
                                        "description": "Success create Anisa Fitri users",
                                        "value": {
                                            "id": "1",
                                            "name": "Anisa Fitri Laila",
                                            "nik": "1234567891123456",
                                            "email": "anisa.fitri@gmail.com"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TsiAuth": []
                    }
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete existing users",
                "description": "Delete existing users in database",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/UserId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success delete users",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Success delete users",
                                        "value": {
                                            "success": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Failed delete not found users",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "failed": {
                                        "description": "Failed delete users",
                                        "value": {
                                            "success": false
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "TsiAuth": {
                "description": "Authentication for Users RESTful API",
                "type": "apiKey",
                "in": "header",
                "name": "X-API-Key"
            }
        },
        "parameters": {
            "UserId": {
                "name": "userId",
                "in": "path",
                "required": true,
                "description": "User id for updated",
                "schema": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 100
                },
                "examples": {
                    "Khairon": {
                        "description": "Sample user id for Khairon",
                        "value": "1"
                    },
                    "Anisa": {
                        "description": "Sample todolist id for Anisa Fitri",
                        "value": "2"
                    }
                }
            }
        },
        "schemas": {
            "login": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "format": "email"
                    },
                    "password": {
                        "type": "string",
                        "format": "password",
                        "minLength": 8
                    }
                }
            },
            "Users": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "nik": {
                        "type": "number",
                        "format": "int64"
                    },
                    "phone": {
                        "type": "number",
                        "format": "int64"
                    }

                }
            },
            "CreateOrUpdateUsers": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "priority": {
                        "type": "number",
                        "format": "int32"
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "ArrayUsers": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Users"
                }
            }
        },
        "examples": {
            "khairon": {
                "description": "Example create users Khairon",
                "value": {
                    "id": 1,
                    "name": "khairon",
                    "nik": 1234567891123456,
                    "email": "khaironbiz@gmail.com"
                }
            },
            "anisa": {
                "description": "Example create users Anisa Fitri Laila",
                "value": {
                    "id": 2,
                    "name": "Anisa Fitri Laila",
                    "nik": 1234567891123456,
                    "email": "anisa.fitri@gmail.com"
                }
            }
        }
    }
}
